version: '3.8'

services:
  # Neon Local Proxy Service
  neon-local:
    image: neondatabase/neon_local:latest
    container_name: acquisitions-neon-local
    ports:
      - '5432:5432'
    env_file:
      - .env.development
    networks:
      - acquisitions-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -p 5432 -U neon']
      interval: 5s
      timeout: 3s
      retries: 5

  # Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acquisitions-app-dev
    ports:
      - '3000:3000'
    env_file:
      - .env.development
    volumes:
      # Mount source code for development (enable hot reload if needed)
      - ./src:/app/src:ro
      - ./logs:/app/logs
      # Mount package.json for dependency changes
      - ./package.json:/app/package.json:ro
    depends_on:
      neon-local:
        condition: service_healthy
    networks:
      - acquisitions-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:3000/health || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  acquisitions-network:
    driver: bridge

volumes:
  logs:
    driver: local
